# Generated by Django 4.1.3 on 2022-12-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_financialdocument_status'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='profile',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.asset', verbose_name='asset'),
            preserve_default=False,
        ),
    ]
