# Generated by Django 3.2.13 on 2022-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for home'),
        ),
    ]
