# Generated by Django 3.2.13 on 2022-05-22 14:05

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('قفل شده', 'قفل شده'), ('آرشیو شده', 'آرشیو شده')], default='پیش نویس', max_length=50, verbose_name='status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'نامه های اداری',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('pre_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='pre_title')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='organization.organizationunit', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'واحد های سازمانی',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='LetterSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraf', models.CharField(max_length=500, verbose_name='paraf')),
                ('description', models.CharField(max_length=5000, verbose_name='paraf')),
                ('date_sent', models.DateTimeField(verbose_name='date sent')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.letter', verbose_name='letter')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_letters', to='organization.organizationunit', verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='organization.organizationunit', verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'LetterSent',
                'verbose_name_plural': 'سیر ارسال نامه ها',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.AddField(
            model_name='letter',
            name='creator_organization_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationunit', verbose_name='واحد ایجاد کننده'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='سرپرست', max_length=50, verbose_name='job title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationunit', verbose_name='organization_unit')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'پرسنل و کارکنان',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
