# Generated by Django 3.2.13 on 2022-05-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220520_0434'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersent',
            name='paraf',
            field=models.CharField(default=1, max_length=500, verbose_name='paraf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lettersent',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
