# Generated by Django 3.2.13 on 2022-05-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettersent',
            options={'verbose_name': 'LetterSent', 'verbose_name_plural': 'LetterSents'},
        ),
    ]
