# Generated by Django 3.2.13 on 2022-04-22 23:51

import core.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام کامل')),
                ('mobile', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان پیام')),
                ('message', models.CharField(max_length=50, verbose_name='متن پیام')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
                ('app_name', models.CharField(choices=[('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('web', 'web'), ('transport', 'transport'), ('log', 'log'), ('map', 'map'), ('market', 'market'), ('stock', 'stock'), ('authentication', 'authentication'), ('dashboard', 'dashboard')], max_length=50, verbose_name='اپلیکیشن')),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'پیام های ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('icon_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon fa')),
                ('icon_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='material_icon')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='svg_icon')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض آیکون')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع آیکون')),
                ('priority', models.IntegerField(default=1000, verbose_name='priority')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='images/Icon/', verbose_name='تصویر آیکون')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Main/', verbose_name='تصویر اصلی')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Header/', verbose_name='تصویر سربرگ')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'تصاویر',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='عنوان')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('short_description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات کوتاه')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات')),
                ('app_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='class_name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('priority', models.IntegerField(default=1000, verbose_name='ترتیب')),
                ('archive', models.BooleanField(default=False, verbose_name='archive?')),
                ('meta_data', models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_data')),
                ('related_pages', models.ManyToManyField(blank=True, to='core.Page', verbose_name='related_pages')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=(models.Model, utility.utils.LinkHelper, core.models.ImageMixin),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('name', models.CharField(max_length=50, verbose_name='نام پارامتر (تغییر ندهید)')),
                ('origin_value', models.CharField(blank=True, max_length=50000, null=True, verbose_name='مقدار پارامتر')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='images/pictures/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.icon')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\phoenix5\\uploads'), upload_to='core/downloads', verbose_name='فایل ضمیمه')),
                ('mirror_link', models.CharField(blank=True, max_length=10000, null=True, verbose_name='آدرس بیرونی')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='اصلاح شده در')),
                ('download_counter', models.IntegerField(default=0, verbose_name='download_counter')),
                ('is_open', models.BooleanField(default=False, verbose_name='is_open?')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
                ('profiles', models.ManyToManyField(blank=True, related_name='profile_downloads', to='authentication.Profile', verbose_name='profiles')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
            bases=('core.icon',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.icon')),
                ('url', models.CharField(max_length=2000, verbose_name='url')),
                ('new_tab', models.BooleanField(default=False, verbose_name='new_tab')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
            bases=('core.icon',),
        ),
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'PageTag',
                'verbose_name_plural': 'PageTags',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write', models.BooleanField(default=False, verbose_name='can write')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'PagePermission',
                'verbose_name_plural': 'PagePermissions',
            },
        ),
        migrations.CreateModel(
            name='PageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'PageLike',
                'verbose_name_plural': 'PageLikes',
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(verbose_name='comment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'PageComment',
                'verbose_name_plural': 'PageComments',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageImage',
                'verbose_name_plural': 'PageImages',
            },
            bases=('core.image', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.link')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageLink',
                'verbose_name_plural': 'PageLinks',
            },
            bases=('core.link', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='PageDownload',
            fields=[
                ('download_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.download')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageDownload',
                'verbose_name_plural': 'PageDownloads',
            },
            bases=('core.download', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.link')),
                ('app_name', models.CharField(choices=[('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('web', 'web'), ('transport', 'transport'), ('log', 'log'), ('map', 'map'), ('market', 'market'), ('stock', 'stock'), ('authentication', 'authentication'), ('dashboard', 'dashboard')], max_length=50, verbose_name='app_name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.navlink', verbose_name='navlink')),
            ],
            options={
                'verbose_name': 'NavLink',
                'verbose_name_plural': 'NavLinks',
            },
            bases=('core.link',),
        ),
    ]
