# Generated by Django 4.0.2 on 2022-03-22 16:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(verbose_name='comment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'PageComment',
                'verbose_name_plural': 'PageComments',
            },
        ),
    ]
