# Generated by Django 4.0.2 on 2022-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='class_name'),
        ),
    ]
