# Generated by Django 3.2.13 on 2022-05-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Header/', verbose_name='تصویر سربرگ'),
        ),
    ]
