# Generated by Django 4.0.2 on 2022-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='new_tab',
            field=models.BooleanField(default=False, verbose_name='new_tab'),
        ),
    ]
