# Generated by Django 4.0.2 on 2022-03-05 00:22

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_app_name_alter_page_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='imagespictures/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='image_origin',
        ),
    ]
