# Generated by Django 3.2.13 on 2022-07-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_header_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
    ]
