# Generated by Django 4.0.2 on 2022-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_picture_remove_parameter_image_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='hgfdsdfggh', max_length=2000, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='ترتیب'),
        ),
    ]
