# Generated by Django 4.0.2 on 2022-03-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_enabled'),
        ('core', '0003_link_new_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام کامل')),
                ('mobile', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان پیام')),
                ('message', models.CharField(max_length=50, verbose_name='متن پیام')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
                ('app_name', models.CharField(choices=[('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('web', 'web'), ('transport', 'transport'), ('log', 'log'), ('map', 'map'), ('market', 'market'), ('stock', 'stock'), ('authentication', 'authentication'), ('dashboard', 'dashboard')], max_length=50, verbose_name='اپلیکیشن')),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'پیام های ارتباط با ما',
            },
        ),
        migrations.RemoveField(
            model_name='icon',
            name='profile',
        ),
        migrations.AddField(
            model_name='download',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.link')),
                ('app_name', models.CharField(choices=[('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('web', 'web'), ('transport', 'transport'), ('log', 'log'), ('map', 'map'), ('market', 'market'), ('stock', 'stock'), ('authentication', 'authentication'), ('dashboard', 'dashboard')], max_length=50, verbose_name='app_name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.navlink', verbose_name='navlink')),
            ],
            options={
                'verbose_name': 'NavLink',
                'verbose_name_plural': 'NavLinks',
            },
            bases=('core.link',),
        ),
    ]
