# Generated by Django 4.0.2 on 2022-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage_remove_icon_profile_download_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_data',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_data'),
        ),
    ]
