# Generated by Django 3.2.13 on 2022-08-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='priority'),
        ),
    ]
