# Generated by Django 4.0.2 on 2022-03-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='imagesImageBase/Header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_main_origin',
            field=models.ImageField(blank=True, null=True, upload_to='imagesImageBase/Main/', verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='imagesImageBase/Thumbnail/', verbose_name='تصویر کوچک'),
        ),
    ]
