# Generated by Django 4.1 on 2022-09-03 20:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='f:\\public\\phoenix5\\uploads'), upload_to='core/downloads', verbose_name='فایل ضمیمه'),
        ),
    ]
