# Generated by Django 4.0.2 on 2022-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parameter_name_alter_parameter_origin_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='core.Page', verbose_name='related_pages'),
        ),
    ]
