# Generated by Django 4.0.2 on 2022-03-09 01:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_image_header_origin_image_image_main_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='imagesImageBase/Thumbnail/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات'),
        ),
    ]
