# Generated by Django 4.1.3 on 2022-12-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_image_creator_image_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_data',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='meta_data'),
        ),
    ]
