# Generated by Django 4.0.2 on 2022-03-25 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_page_related_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelike',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
