# Generated by Django 4.0.2 on 2022-03-12 11:47

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilecontact_membershiprequest'),
        ('core', '0007_page_thumbnail_origin_alter_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='id',
        ),
        migrations.RemoveField(
            model_name='download',
            name='name',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='name',
        ),
        migrations.AddField(
            model_name='download',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='افزوده شده در'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='اصلاح شده در'),
        ),
        migrations.AddField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\phoenix5\\uploads'), upload_to='core/downloads', verbose_name='فایل ضمیمه'),
        ),
        migrations.AddField(
            model_name='download',
            name='icon_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='is_open?'),
        ),
        migrations.AddField(
            model_name='download',
            name='mirror_link',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='آدرس بیرونی'),
        ),
        migrations.AddField(
            model_name='download',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profile_downloads', to='authentication.Profile', verbose_name='profiles'),
        ),
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.link')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageLink',
                'verbose_name_plural': 'PageLinks',
            },
            bases=('core.link', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='PageDownload',
            fields=[
                ('download_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.download')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageDownload',
                'verbose_name_plural': 'PageDownloads',
            },
            bases=('core.download', utility.utils.LinkHelper),
        ),
    ]
