# Generated by Django 4.1.7 on 2023-03-23 21:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_page_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\public\\uploads\\phoenix5'), upload_to='core/downloads', verbose_name='فایل ضمیمه'),
        ),
    ]
