# Generated by Django 4.0.2 on 2022-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilecontact_membershiprequest'),
        ('core', '0008_remove_download_id_remove_download_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon fa'),
        ),
        migrations.CreateModel(
            name='PageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'PageLike',
                'verbose_name_plural': 'PageLikes',
            },
        ),
    ]
