# Generated by Django 4.0.2 on 2022-03-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilecontact_membershiprequest'),
        ('core', '0009_icon_priority_alter_icon_icon_fa_pagelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
        ),
    ]
