# Generated by Django 4.0.2 on 2022-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_icon_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='download_counter',
            field=models.IntegerField(default=0, verbose_name='download_counter'),
        ),
    ]
