# Generated by Django 4.0.2 on 2022-03-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_download_download_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='archive?'),
        ),
    ]
