# Generated by Django 4.0.2 on 2022-03-19 00:50

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نقطه')),
                ('location', models.CharField(max_length=1000, verbose_name='لوکیشن')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='longitude')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maplocation_set', to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'لوکیشن',
                'verbose_name_plural': 'لوکیشن ها',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
