# Generated by Django 4.0.2 on 2022-03-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag_pagetag'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.location', verbose_name='location')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageLocation',
                'verbose_name_plural': 'PageLocations',
            },
        ),
    ]
