# Generated by Django 3.2.2 on 2021-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20211108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='asdsads', max_length=100, verbose_name='عنوان نقطه'),
            preserve_default=False,
        ),
    ]
