# Generated by Django 3.2.13 on 2022-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0002_gameact'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameact',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
