# Generated by Django 3.2.13 on 2022-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0003_gameact_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('در حال افزودن بازیکنان', 'در حال افزودن بازیکنان'), ('در حال افزودن نقش', 'در حال افزودن بازیکنان'), ('شروع شده', 'شروع شده'), ('پایان یافته', 'پایان یافته')], default='ایجاد شده', max_length=50, verbose_name='status'),
        ),
    ]
