# Generated by Django 3.2.13 on 2022-05-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0004_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mafia.player', verbose_name='player'),
        ),
    ]
