# Generated by Django 4.1 on 2022-10-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_productspecification_name_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile',
        ),
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account'),
            preserve_default=False,
        ),
    ]
