# Generated by Django 3.2.13 on 2022-08-26 22:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(max_length=5000, verbose_name='question')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.exam', verbose_name='exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='number')),
                ('option', tinymce.models.HTMLField(max_length=5000, verbose_name='question')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
