# Generated by Django 4.1 on 2022-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('school', '0002_remove_student_profile_remove_teacher_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(blank=True, to='library.book', verbose_name='books'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
