# Generated by Django 4.1 on 2022-10-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_books_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب'), ('نا مشخص', 'نا مشخص'), ('تاخیر', 'تاخیر'), ('تشویق', 'تشویق'), ('تنبیه', 'تنبیه'), ('ارزیابی', 'ارزیابی')], max_length=50, verbose_name='status'),
        ),
    ]
