# Generated by Django 4.1.3 on 2022-12-01 15:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_financialdocument_status'),
        ('school', '0005_alter_attendance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='school',
            name='account',
            field=models.ForeignKey(default=82, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='option'),
        ),
    ]
