# Generated by Django 4.1.3 on 2023-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_warehousesheet_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheet',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('گرم', 'گرم'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('لینک', 'لینک'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
    ]
