# Generated by Django 3.2.13 on 2022-04-22 23:51

import core.models
from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='market/images/Category/Thumbnail/', verbose_name='تصویر کوچک')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('for_home', models.BooleanField(default=False, verbose_name='for_home')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='market.category', verbose_name='parent')),
                ('products', models.ManyToManyField(blank=True, to='accounting.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(models.Model, utility.utils.LinkHelper, core.models.ImageMixin),
        ),
    ]
