# Generated by Django 3.2.13 on 2022-06-11 23:08

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_asset_price'),
        ('market', '0002_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shop',
            name='available',
            field=models.IntegerField(default=1, verbose_name='available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='product_or_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.productorservice', verbose_name='product_or_service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'CartLine',
                'verbose_name_plural': 'CartLines',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
