# Generated by Django 4.0.2 on 2022-04-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cart_category_parent_alter_category_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for_home'),
        ),
    ]
