# Generated by Django 3.2.13 on 2022-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_productorservice_barcode'),
        ('market', '0003_auto_20220612_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, to='accounting.Product', verbose_name='products'),
        ),
    ]
