# Generated by Django 4.0.2 on 2022-04-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_category_for_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Category/Thumbnail/', verbose_name='تصویر کوچک'),
        ),
    ]
