# Generated by Django 3.2.13 on 2022-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_shop_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Category/Header/', verbose_name='تصویر سربرگ'),
        ),
    ]
