# Generated by Django 3.2.13 on 2022-08-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_category_header_origin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
