# Generated by Django 4.1 on 2022-09-29 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('accounting', '0020_productspecification'),
        ('market', '0008_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'مشتری عادی'), ('همکار', 'همکار')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='expire_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 21, 2, 47, 472870, tzinfo=datetime.timezone.utc), verbose_name='تاریخ اعتبار تا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'مشتری عادی'), ('همکار', 'همکار')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='accounting.productspecification', verbose_name='ویژگی ها'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='region'),
            preserve_default=False,
        ),
    ]
