# Generated by Django 4.1 on 2022-10-15 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_customer_level_customer_region_shop_expire_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartline',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='row',
            field=models.IntegerField(blank=True, default=1, verbose_name='row'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartline',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='market.customer', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.FloatField(verbose_name='quantity'),
        ),
    ]
