# Generated by Django 4.1 on 2022-10-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_cartline_date_added_cartline_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.FloatField(verbose_name='تعداد'),
        ),
    ]
