# Generated by Django 4.1 on 2022-10-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_invoiceline_unit_name_alter_price_unit_name_and_more'),
        ('market', '0011_alter_cartline_customer_alter_cartline_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'MarketInvoice',
                'verbose_name_plural': 'MarketInvoices',
            },
            bases=('accounting.invoice',),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='region',
        ),
        migrations.AddField(
            model_name='shop',
            name='buy_price',
            field=models.IntegerField(default=1, verbose_name='buy_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='old_price',
            field=models.IntegerField(default=1, verbose_name='old_price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('گرم', 'گرم'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('لینک', 'لینک'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
    ]
