# Generated by Django 4.1 on 2022-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_marketinvoice_remove_shop_region_shop_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='row',
            field=models.IntegerField(blank=True, default=1, verbose_name='row'),
        ),
    ]
