# Generated by Django 4.1.3 on 2022-12-23 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_cartline_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.customer', verbose_name='inviter'),
        ),
    ]
