# Generated by Django 3.2.2 on 2022-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='desciption',
        ),
        migrations.AddField(
            model_name='log',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name'),
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='description'),
        ),
    ]
