# Generated by Django 4.1.3 on 2023-01-20 16:41

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0028_bankaccount_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ProfileContact',
                'verbose_name_plural': 'ProfileContacts',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('موبایل', 'موبایل'), ('تلفن', 'تلفن'), ('فکس', 'فکس'), ('ایمیل', 'ایمیل'), ('واتسپ', 'واتسپ'), ('تلگرام', 'تلگرام'), ('یوتوب', 'یوتوب'), ('اینستاگرام', 'آدرس'), ('آدرس', 'آدرس'), ('وب سایت', 'وب سایت')], default='موبایل', max_length=50, verbose_name='name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('url', models.CharField(blank=True, max_length=5000, null=True, verbose_name='url')),
                ('icon', models.CharField(blank=True, max_length=5000, null=True, verbose_name='icon')),
                ('bs_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='bootstrap class')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
