# Generated by Django 4.0.2 on 2022-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_countdownitem_faq_technology_testimonial_ourteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='app_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for_home'),
        ),
        migrations.AddField(
            model_name='feature',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for_home'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for_home'),
        ),
    ]
