# Generated by Django 4.1 on 2022-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال'),
        ),
    ]
