# Generated by Django 4.1 on 2022-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0002_alter_guarantee_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='serial_no',
            field=models.CharField(default='0000', max_length=50, verbose_name='شماره سریال'),
            preserve_default=False,
        ),
    ]
