# Generated by Django 4.0.2 on 2022-04-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0003_remove_guarantee_invoice_guarantee_invoice_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantee',
            name='product',
        ),
    ]
