# Generated by Django 4.0.2 on 2022-03-17 14:42

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_download_download_counter'),
        ('accounting', '0010_financialdocument_bedehkar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('job_title', models.CharField(max_length=50, verbose_name='job title')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.product')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
            bases=('accounting.product',),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='projectmanager.organizationunit', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'OrganizationUnits',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='PM_Service',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
            bases=('accounting.service',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_contracted', to='projectmanager.organizationunit', verbose_name='پیمانکار')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_employed', to='projectmanager.organizationunit', verbose_name='کارفرما')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
                ('project_id', models.IntegerField(verbose_name='project_id')),
            ],
            options={
                'verbose_name': 'ProjectInvoice',
                'verbose_name_plural': 'ProjectInvoices',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit_price', models.IntegerField(verbose_name='unit_price')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('فنجان', 'فنجان'), ('جفت', 'جفت')], default='عدد', max_length=50, verbose_name='unit_name')),
                ('date_requested', models.DateTimeField(verbose_name='date_requested')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال انجام', 'در حال انجام'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما'), ('موجود در انبار', 'موجود در انبار'), ('خارج شده از انبار', 'خارج شده از انبار'), ('وارد شده به انبار', 'وارد شده به انبار')], max_length=50, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
                ('product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.productorservice', verbose_name='product or service')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
            ],
            options={
                'verbose_name': 'SampleForm',
                'verbose_name_plural': 'فرم های اداری نمونه',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='MaterialInvoice',
            fields=[
                ('projectinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectinvoice')),
            ],
            options={
                'verbose_name': 'MaterialInvoice',
                'verbose_name_plural': 'MaterialInvoices',
            },
            bases=('projectmanager.projectinvoice',),
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('projectinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectinvoice')),
            ],
            options={
                'verbose_name': 'ServiceInvoice',
                'verbose_name_plural': 'ServiceInvoices',
            },
            bases=('projectmanager.projectinvoice',),
        ),
        migrations.CreateModel(
            name='RequestSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید'), ('درخواست شده', 'درخواست شده'), ('تسویه شده', 'تسویه شده')], default='درخواست شده', max_length=200, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'RequestSignature',
                'verbose_name_plural': 'RequestSignatures',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.organizationunit', verbose_name='organization_unit'),
        ),
    ]
