# Generated by Django 4.0.2 on 2022-03-18 15:06

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
            bases=('projectmanager.request', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'ServiceRequest',
                'verbose_name_plural': 'ServiceRequests',
            },
            bases=('projectmanager.request', utility.utils.LinkHelper),
        ),
    ]
