# Generated by Django 4.0.2 on 2022-04-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pm_service',
        #     name='service_ptr',
        # ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='PM_Service',
        ),
    ]
