# Generated by Django 4.0.2 on 2022-03-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link_new_tab'),
        ('map', '0001_initial'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('event_datetime', models.DateTimeField(verbose_name='event_datetime')),
                ('start_datetime', models.DateTimeField(verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end_datetime')),
                ('locations', models.ManyToManyField(blank=True, to='map.Location', verbose_name='locations')),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'رویداد ها',
            },
            bases=('core.page',),
        ),
    ]
