# Generated by Django 4.0.2 on 2022-03-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_location_latitude_alter_location_longitude'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(blank=True, to='map.Location', verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_units',
            field=models.ManyToManyField(blank=True, to='projectmanager.OrganizationUnit', verbose_name='واحد های سازمانی'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_completed',
            field=models.IntegerField(default=0, verbose_name='درصد تکمیل پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('تعریف اولیه', 'تعریف اولیه'), ('پیش نویس', 'پیش نویس'), ('تحویل شده', 'تحویل شده'), ('در حال اجرا', 'درحال اجرا'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('کنسل شده', 'کنسل شده'), ('تسویه شده', 'تسویه شده')], default='پیش نویس', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='project',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='ضریب و وزن پروژه'),
        ),
    ]
