# Generated by Django 4.0.2 on 2022-03-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_materialrequest_servicerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'verbose_name': 'MaterialRequest', 'verbose_name_plural': 'درخواست های متریال'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'ServiceRequest', 'verbose_name_plural': 'درخواست های سرویس'},
        ),
    ]
