# Generated by Django 4.0.2 on 2022-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_project_end_date_project_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='pre_title',
            field=models.CharField(default='', max_length=50, verbose_name='pre_title'),
        ),
    ]
