# Generated by Django 4.0.2 on 2022-03-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='سرپرست', max_length=50, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.organizationunit', verbose_name='organization_unit'),
        ),
    ]
