# Generated by Django 4.0.2 on 2022-03-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagelike_date_added'),
        ('projectmanager', '0003_alter_employee_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letters',
            },
            bases=('core.page',),
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'WareHouse', 'verbose_name_plural': 'WareHouses'},
        ),
    ]
