# Generated by Django 4.0.2 on 2022-03-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_organizationunit_pre_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('organizationunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.organizationunit')),
            ],
            bases=('projectmanager.organizationunit',),
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'verbose_name': 'OrganizationUnit', 'verbose_name_plural': 'واحد های سازمانی'},
        ),
    ]
