# Generated by Django 4.0.2 on 2022-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_warehouse_alter_organizationunit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='pre_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pre_title'),
        ),
    ]
