# Generated by Django 4.1.7 on 2023-05-27 01:48

from django.db import migrations, models
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20220825_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active_directory', models.CharField(blank=True, max_length=100, null=True, verbose_name='active_directory')),
                ('work_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='work_group')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='local_ip')),
                ('remote_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='remote_ip')),
                ('any_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_address')),
                ('any_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_password')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='password')),
                ('identity', models.CharField(blank=True, max_length=50, null=True, verbose_name='identity')),
                ('ssid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ssid')),
                ('preshared_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='preshared_key')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='frequency')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='protocol')),
                ('channel_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='channel_width')),
                ('adsl_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_username')),
                ('adsl_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_password')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='telephone')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'RemoteClient',
                'verbose_name_plural': 'RemoteClients',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.AddField(
            model_name='project',
            name='remote_clients',
            field=models.ManyToManyField(blank=True, to='projectmanager.remoteclient', verbose_name='کلاینت ها'),
        ),
    ]
