# Generated by Django 4.0.2 on 2022-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_letter_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='letterSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(verbose_name='date sent')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.letter', verbose_name='letter')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_letters', to='projectmanager.organizationunit', verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='projectmanager.organizationunit', verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'letterSend',
                'verbose_name_plural': 'letterSends',
            },
        ),
    ]
