# Generated by Django 4.0.2 on 2022-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_lettersend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='letterSend',
            new_name='letterSent',
        ),
        migrations.AlterModelOptions(
            name='lettersent',
            options={'verbose_name': 'letterSent', 'verbose_name_plural': 'letterSents'},
        ),
    ]
