# Generated by Django 4.0.2 on 2022-03-17 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_alter_organizationunit_pre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_delivered'),
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('درخواست متریال', 'درخواست متریال'), ('درخواست سرویس', 'درخواست سرویس')], default='درخواست متریال', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_requested'),
        ),
    ]
