# Generated by Django 4.0.2 on 2022-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_rename_lettersend_lettersent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='locations',
        ),
    ]
