# Generated by Django 4.0.2 on 2022-03-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_remove_project_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locations',
        ),
    ]
