# Generated by Django 3.2.13 on 2022-05-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default='sdssdsd', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
