# Generated by Django 3.2.13 on 2022-05-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('polls', '0002_option_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='creator'),
            preserve_default=False,
        ),
    ]
