# Generated by Django 3.2.13 on 2022-05-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه')),
                ('bio', models.CharField(blank=True, max_length=50, null=True, verbose_name='بیو')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='تصویر')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/header/', verbose_name='سربرگ')),
                ('enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('can_login', models.BooleanField(default=False, verbose_name='لاگین می کند ?')),
                ('status', models.CharField(choices=[('AAA', 'AAA'), ('BBB', 'BBB')], default='AAA', max_length=50, verbose_name='وضعیت')),
                ('default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='ProfileContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('url', models.CharField(blank=True, max_length=5000, null=True, verbose_name='url')),
                ('icon', models.CharField(blank=True, max_length=5000, null=True, verbose_name='icon')),
                ('bs_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='bootstrap class')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ProfileContact',
                'verbose_name_plural': 'ProfileContacts',
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, verbose_name='mobile')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('read', models.BooleanField(default=False, verbose_name='read?')),
                ('handled', models.BooleanField(default=False, verbose_name='handled?')),
                ('date_handled', models.DateTimeField(blank=True, null=True, verbose_name='date_handled')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'MembershipRequest',
                'verbose_name_plural': 'MembershipRequests',
            },
        ),
    ]
