# Generated by Django 3.2.13 on 2022-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecontact',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
    ]
