# Generated by Django 3.2.13 on 2022-05-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بیو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='لاگین می کند ?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default',
            field=models.BooleanField(default=False, verbose_name='پیش فرض'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/header/', verbose_name='سربرگ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('AAA', 'AAA'), ('BBB', 'BBB')], default='AAA', max_length=50, verbose_name='وضعیت'),
        ),
    ]
