# Generated by Django 4.0.2 on 2022-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
    ]
