# Generated by Django 4.1 on 2022-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilecontact_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontact',
            name='name',
            field=models.CharField(choices=[('موبایل', 'موبایل'), ('تلفن', 'تلفن'), ('فکس', 'فکس'), ('ایمیل', 'ایمیل'), ('واتسپ', 'واتسپ'), ('تلگرام', 'تلگرام'), ('یوتوب', 'یوتوب'), ('اینستاگرام', 'آدرس'), ('آدرس', 'آدرس'), ('وب سایت', 'وب سایت')], default='موبایل', max_length=50, verbose_name='name'),
        ),
    ]
