# Generated by Django 4.0.2 on 2022-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
