# Generated by Django 4.1.3 on 2023-03-01 23:16

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organizationunit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='جهت')),
            ],
            options={
                'verbose_name': 'SalaryItem',
                'verbose_name_plural': 'SalaryItems',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('start_time', models.TimeField(verbose_name='شروع')),
                ('end_time', models.TimeField(verbose_name='پایان')),
                ('enter_start_time', models.TimeField(verbose_name='شروع ورود')),
                ('enter_end_time', models.TimeField(verbose_name='پایان ورود')),
                ('exit_start_time', models.TimeField(verbose_name='شروع خروج')),
                ('exit_end_time', models.TimeField(verbose_name='پایان خروج')),
                ('enter_delay', models.IntegerField(default=0, verbose_name='تاخیر ورود')),
                ('exit_hurry', models.IntegerField(default=0, verbose_name='تعجیل خروج')),
                ('day_count', models.IntegerField(default=1, verbose_name='روز کاری')),
                ('rest_start', models.TimeField(verbose_name='شروع استراحت')),
                ('rest_end', models.TimeField(verbose_name='پایان استراحت')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTables',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('saturday', models.BooleanField(verbose_name='شنبه')),
                ('sunday', models.BooleanField(verbose_name='یکشنبه')),
                ('monday', models.BooleanField(verbose_name='دوشنبه')),
                ('tuesday', models.BooleanField(verbose_name='سه شنبه')),
                ('wednesday', models.BooleanField(verbose_name='چهار شنبه')),
                ('thursday', models.BooleanField(verbose_name='پنج شنبه')),
                ('friday', models.BooleanField(verbose_name='جمعه')),
                ('time_tables', models.ManyToManyField(to='salary.timetable', verbose_name='جدول های زمانی')),
            ],
            options={
                'verbose_name': 'WorkShift',
                'verbose_name_plural': 'WorkShifts',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='جهت')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salarys',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0, verbose_name='ماه')),
                ('year', models.IntegerField(default=0, verbose_name='سال')),
                ('delay', models.IntegerField(default=0, verbose_name='تاخیر')),
                ('hurry', models.IntegerField(default=0, verbose_name='تعجیل')),
                ('leave', models.IntegerField(default=0, verbose_name='مرخصی')),
                ('rest', models.IntegerField(default=0, verbose_name='استراحت')),
                ('duration', models.IntegerField(default=0, verbose_name='دقایق حضور')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب'), ('تاخیر', 'تاخیر'), ('ثبت نشده', 'ثبت نشده')], default='ثبت نشده', max_length=100, verbose_name='وضعیت')),
                ('date_registered', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'رکورد حضور و غیاب',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('مدیر', 'مدیر'), ('کارمند', 'کارمند'), ('سایر', 'سایر')], default='کارمند', max_length=100, verbose_name='نوع')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('employees', models.ManyToManyField(blank=True, to='organization.employee', verbose_name='پرسنل')),
                ('rows', models.ManyToManyField(blank=True, to='salary.salaryitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='EmployeeTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='پرسنل')),
                ('work_shifts', models.ManyToManyField(to='salary.workshift', verbose_name='workshifts')),
            ],
            options={
                'verbose_name': 'EmployeeTiming',
                'verbose_name_plural': 'EmployeeTimings',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='EmployeeCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ورود', 'ورود'), ('ورود ساعتی', 'ورود ساعتی'), ('خروج', 'خروج'), ('خروج ساعتی', 'خروج ساعتی'), ('غیر معتبر', 'غیر معتبر')], max_length=50, verbose_name='نوع تردد')),
                ('cross_datetime', models.DateTimeField(verbose_name='تاریخ و ساعت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'EmployeeCross',
                'verbose_name_plural': 'EmployeeCrosss',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='تاریخ')),
                ('delay', models.IntegerField(default=0, verbose_name='تاخیر')),
                ('hurry', models.IntegerField(default=0, verbose_name='تعجیل')),
                ('leave', models.IntegerField(default=0, verbose_name='مرخصی')),
                ('rest', models.IntegerField(default=0, verbose_name='استراحت')),
                ('duration', models.IntegerField(default=0, verbose_name='دقایق حضور')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب'), ('تاخیر', 'تاخیر'), ('ثبت نشده', 'ثبت نشده')], default='ثبت نشده', max_length=100, verbose_name='وضعیت')),
                ('date_registered', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'رکورد حضور و غیاب',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
