# Generated by Django 4.1.3 on 2023-02-01 00:32

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0030_alter_invoiceline_unit_name_alter_price_unit_name_and_more'),
        ('organization', '0002_alter_organizationunit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='direction')),
            ],
            options={
                'verbose_name': 'SalaryItem',
                'verbose_name_plural': 'SalaryItems',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('month', models.IntegerField(verbose_name='month')),
                ('year', models.IntegerField(verbose_name='year')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='direction')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salarys',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('type', models.CharField(choices=[('مدیر', 'مدیر'), ('کارمند', 'کارمند'), ('سایر', 'سایر')], default='کارمند', max_length=100, verbose_name='type')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('employees', models.ManyToManyField(blank=True, to='organization.employee', verbose_name='employees')),
                ('rows', models.ManyToManyField(blank=True, to='salary.salaryitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField(default=0, verbose_name='delay')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب'), ('تاخیر', 'تاخیر'), ('ثبت نشده', 'ثبت نشده')], default='ثبت نشده', max_length=100, verbose_name='status')),
                ('date_registered', models.DateTimeField(verbose_name='date_registered')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'رکورد حضور و غیاب',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
