# Generated by Django 4.1.7 on 2023-03-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'verbose_name': 'DailyAttendance', 'verbose_name_plural': 'DailyAttendances'},
        ),
        migrations.AlterModelOptions(
            name='monthlyattendance',
            options={'verbose_name': 'MonthlyAttendance', 'verbose_name_plural': 'MonthlyAttendances'},
        ),
    ]
