# Generated by Django 4.0.2 on 2022-03-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagelike_date_added'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='archive.folder', verbose_name='folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
            bases=('core.page',),
        ),
    ]
