# Generated by Django 4.1 on 2022-10-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profilecontact_name'),
        ('archive', '0002_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_owned', to='authentication.profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='folder',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='authentication.profile', verbose_name='profile'),
        ),
    ]
