# Generated by Django 4.1 on 2022-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_folder_owner_folder_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='ترتیب'),
        ),
    ]
