# Generated by Django 4.1 on 2022-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_folder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public?'),
        ),
    ]
