# Generated by Django 4.1 on 2022-10-29 11:47

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_invoiceline_row'),
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('date_served', models.DateField(verbose_name='date_served')),
                ('meal_type', models.CharField(choices=[('صبحانه', 'صبحانه'), ('ناهار', 'ناهار'), ('شام', 'شام')], max_length=50, verbose_name='meal type')),
                ('max_reserve', models.IntegerField(default=100, verbose_name='max')),
                ('reserved', models.IntegerField(default=1, verbose_name='reserved')),
                ('foods', models.ManyToManyField(to='chef.food', verbose_name='food')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='ReservedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('date_reserved', models.DateTimeField(auto_now_add=True, verbose_name='date_reserved')),
                ('date_served', models.DateTimeField(blank=True, null=True, verbose_name='date_served')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.guest', verbose_name='guest')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.meal', verbose_name='meal')),
            ],
            options={
                'verbose_name': 'ReservedMeal',
                'verbose_name_plural': 'ReservedMeals',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
