# Generated by Django 4.1.3 on 2022-12-25 01:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='body'),
        ),
    ]
