# Generated by Django 4.1.3 on 2022-12-20 00:32

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0025_financialdocument_status'),
        ('market', '0013_alter_cartline_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('percentage', models.IntegerField(verbose_name='percentage')),
            ],
            options={
                'verbose_name': 'Coef',
                'verbose_name_plural': 'Coefs',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, verbose_name='sum')),
                ('ship_fee', models.IntegerField(default=0, verbose_name='هزینه حمل')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('date_ordered', models.DateTimeField(verbose_name='date_ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='accounting.invoice', verbose_name='invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyclub.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
