# Generated by Django 4.1.3 on 2022-12-17 01:41

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0013_alter_cartline_row'),
        ('accounting', '0025_financialdocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('sum', models.IntegerField(default=0, verbose_name='sum')),
                ('date_ordered', models.DateTimeField(verbose_name='date_ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='accounting.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
