# Generated by Django 4.1.3 on 2022-12-19 20:21

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_cartline_row'),
        ('loyaltyclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_amount', models.IntegerField(default=0, verbose_name='coupon_amount')),
                ('cash_amount', models.IntegerField(default=0, verbose_name='coupon_amount')),
                ('date_paid', models.DateTimeField(verbose_name='date paid')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
