# Generated by Django 4.1.3 on 2022-12-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_financialdocument_status'),
        ('loyaltyclub', '0002_remove_coupon_amount_remove_coupon_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPay',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.transaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltyclub.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'DiscountPay',
                'verbose_name_plural': 'DiscountPays',
            },
            bases=('accounting.transaction',),
        ),
    ]
