# Generated by Django 4.1.7 on 2023-04-04 01:53

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('accounting', '0032_account_mobile_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='region')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='Packer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='region')),
            ],
            options={
                'verbose_name': 'Packer',
                'verbose_name_plural': 'Packers',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
