# Generated by Django 4.1.7 on 2023-04-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_account_mobile_alter_transaction_status'),
        ('snapp', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='products_or_services',
            field=models.ManyToManyField(blank=True, to='accounting.productorservice', verbose_name='products_or_services'),
        ),
    ]
