# Generated by Django 4.1.7 on 2023-04-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_shop_unit_name'),
        ('snapp', '0003_menu_products_or_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='products_or_services',
        ),
        migrations.AddField(
            model_name='menu',
            name='shops',
            field=models.ManyToManyField(blank=True, to='market.shop', verbose_name='shops'),
        ),
    ]
