# Generated by Django 3.2.13 on 2022-04-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='color_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color', verbose_name='color'),
        ),
    ]
