# Generated by Django 4.0.2 on 2022-04-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocument',
            name='document_datetime',
        ),
    ]
