# Generated by Django 3.2.13 on 2022-05-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='default_account',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
