# Generated by Django 4.0.2 on 2022-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_price_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/account/', verbose_name='logo'),
        ),
    ]
