# Generated by Django 4.0.2 on 2022-03-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_transaction_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='productorservice',
            new_name='product_or_service',
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice', verbose_name='invoice'),
        ),
    ]
