# Generated by Django 3.2.13 on 2022-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_bankaccount_default_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
