# Generated by Django 4.0.2 on 2022-03-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_account_logo_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'پرداخت ها'},
        ),
    ]
