# Generated by Django 3.2.13 on 2022-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorservice',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد'),
        ),
    ]
