# Generated by Django 4.0.2 on 2022-03-07 16:37

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_link_url_page_priority'),
        ('accounting', '0003_rename_productorservice_invoiceline_product_or_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
            bases=('core.page', utility.utils.LinkHelper),
        ),
        migrations.CreateModel(
            name='FinancialDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'FinancialDocumentTag',
                'verbose_name_plural': 'FinancialDocumentTags',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transactioncategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='accounting.account', verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='accounting.account', verbose_name='دریافت کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(verbose_name='تاریخ تراکنش'),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounting.FinancialDocumentTag', verbose_name='tags'),
        ),
    ]
