# Generated by Django 3.2.13 on 2022-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=5000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='account',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/account/', verbose_name='لوگو ن تصویر'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('پرداخت نشده', 'پرداخت نشده'), ('همراه بانک', 'همراه بانک'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('کارت به کارت', 'کارت به کارت'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('تحویل شده', 'تحویل شده'), ('تایید شده', 'تایید شده'), ('کنسل شده', 'کنسل شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت'),
        ),
    ]
