# Generated by Django 3.2.13 on 2022-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20220512_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/account/', verbose_name='لوگو , تصویر'),
        ),
    ]
