# Generated by Django 3.2.13 on 2022-07-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_productorservice_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='economic_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره اقتصادی'),
        ),
        migrations.AddField(
            model_name='account',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فکس'),
        ),
        migrations.AddField(
            model_name='account',
            name='melli_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='account',
            name='register_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ثبت'),
        ),
    ]
