# Generated by Django 4.0.2 on 2022-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorservice',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='buy_price'),
        ),
        migrations.AddField(
            model_name='productorservice',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='sell_price'),
        ),
        migrations.AddField(
            model_name='productorservice',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('فنجان', 'فنجان'), ('جفت', 'جفت')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
    ]
