# Generated by Django 4.0.2 on 2022-03-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_productorservice_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorservice',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='productorservice',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='productorservice',
            name='unit_name',
        ),
    ]
