# Generated by Django 4.0.2 on 2022-03-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wage',
            new_name='Salary',
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
    ]
