# Generated by Django 4.0.2 on 2022-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_productorservice_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='direction',
            field=models.CharField(choices=[('بدهکار', 'بدهکار'), ('بستانکار', 'بستانکار')], default='بستانکار', max_length=50, verbose_name='direction'),
        ),
    ]
