# Generated by Django 4.0.2 on 2022-03-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_rename_wage_salary_alter_salary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='misc',
            field=models.IntegerField(default=0, verbose_name='سایر'),
        ),
        migrations.CreateModel(
            name='FinancialSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.financialsubaccount', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'FinancialSubAccount',
                'verbose_name_plural': 'FinancialSubAccounts',
            },
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.financialsubaccount', verbose_name='Financial Sub Account'),
        ),
    ]
