# Generated by Django 4.0.2 on 2022-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_financialdocument_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialbalance',
            name='title',
            field=models.CharField(choices=[('حساب عادی', 'حساب عادی'), ('سرمایه گذاری', 'سرمایه گذاری'), ('دارایی', 'دارایی'), ('ملک', 'ملک'), ('اثاثیه', 'اثاثیه'), ('مالیات', 'مالیات'), ('هزینه', 'هزینه'), ('حقوق', 'حقوق'), ('فروش', 'فروش'), ('خرید', 'خرید'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='title'),
        ),
    ]
