# Generated by Django 3.2.13 on 2022-07-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20220730_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ProductOrServiceCategory',
                'verbose_name_plural': 'ProductOrServiceCategories',
            },
        ),
        migrations.RemoveField(
            model_name='productorservice',
            name='category_title',
        ),
        migrations.AddField(
            model_name='productorservice',
            name='product_or_service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.productorservicecategory', verbose_name='دسته بندی'),
        ),
    ]
