# Generated by Django 4.0.2 on 2022-03-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_financialbalance_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='ware_house',
        ),
        migrations.DeleteModel(
            name='Guarantee',
        ),
        migrations.DeleteModel(
            name='WareHouse',
        ),
        migrations.DeleteModel(
            name='WareHouseSheet',
        ),
    ]
