# Generated by Django 3.2.13 on 2022-08-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20220730_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='priority'),
        ),
    ]
