# Generated by Django 4.0.2 on 2022-03-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_warehouse_owner_remove_warehouse_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tel'),
        ),
    ]
