# Generated by Django 4.0.2 on 2022-03-09 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_subaccount_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='bedehkar'),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='bestankar'),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='document_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='document_datetime'),
            preserve_default=False,
        ),
    ]
