# Generated by Django 4.0.2 on 2022-03-17 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_financialdocument_bedehkar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
