# Generated by Django 4.0.2 on 2022-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_account_address_account_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_name',
            field=models.CharField(default='accounting', max_length=50, verbose_name='app_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='class_name',
            field=models.CharField(default='account', max_length=50, verbose_name='class_name'),
            preserve_default=False,
        ),
    ]
