# Generated by Django 4.0.2 on 2022-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_account_app_name_account_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='class_name'),
        ),
    ]
