# Generated by Django 4.0.2 on 2022-03-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_invoiceline_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocument',
            name='sub_account',
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.subaccount', verbose_name='Sub Account'),
        ),
    ]
