# Generated by Django 3.2.13 on 2022-08-19 16:26

import core.models
from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('فروش کالا', 'فروش کالا'), ('فروش خدمات', 'فروش خدمات'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/Category/Thumbnail/', verbose_name='تصویر کوچک')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/Category/Header/', verbose_name='تصویر سربرگ')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('for_home', models.BooleanField(default=False, verbose_name='for_home')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='accounting.category', verbose_name='parent')),
                ('products_or_services', models.ManyToManyField(blank=True, to='accounting.ProductOrService', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=(models.Model, utility.utils.LinkHelper, core.models.ImageMixin),
        ),
    ]
