# Generated by Django 3.2.13 on 2022-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20220819_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products_or_services',
            field=models.ManyToManyField(blank=True, to='accounting.ProductOrService', verbose_name='products or services'),
        ),
    ]
