# Generated by Django 4.0.2 on 2022-03-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_subaccount_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialbalance',
            name='buy_service',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='sell_benefit',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='sell_loss',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='sell_service',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='ship_fee',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='financialbalance',
            name='wage',
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='بدهکار'),
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='بستانکار'),
        ),
    ]
