# Generated by Django 4.1 on 2022-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_category_products_or_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='print_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ چاپ'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.CharField(choices=[('هزینه آب', 'هزینه آب'), ('هزینه اجاره', 'هزینه اجاره'), ('هزینه اینترنت', 'هزینه اینترنت'), ('هزینه برق', 'هزینه برق'), ('هزینه تلفن', 'هزینه تلفن'), ('هزینه حمل ونقل', 'هزینه حمل ونقل'), ('هزینه خوراک', 'هزینه خوراک'), ('هزینه دارو و سلامت', 'هزینه دارو و سلامت'), ('هزینه گاز', 'هزینه گاز'), ('هزینه موبایل', 'هزینه موبایل')], max_length=50, verbose_name='cost'),
        ),
    ]
