# Generated by Django 4.0.2 on 2022-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_financialbalance_buy_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='title',
            field=models.CharField(choices=[('حساب عادی', 'حساب عادی'), ('سرمایه گذاری', 'سرمایه گذاری'), ('دارایی', 'دارایی'), ('ملک', 'ملک'), ('اثاثیه', 'اثاثیه'), ('مالیات', 'مالیات'), ('هزینه', 'هزینه'), ('فروش', 'فروش'), ('خرید', 'خرید'), ('سایر', 'سایر')], default='حساب عادی', max_length=50, verbose_name='title'),
        ),
    ]
