# Generated by Django 4.1 on 2022-09-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_transaction_print_datetime_alter_cost_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('تحویل شده', 'تحویل شده'), ('تایید شده', 'تایید شده'), ('کنسل شده', 'کنسل شده'), ('برگشت از تحویل', 'برگشت از تحویل'), ('تایید نهایی شده', 'تایید نهایی شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت'),
        ),
    ]
