# Generated by Django 4.1 on 2022-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorservice',
            name='product_or_service_category',
        ),
        migrations.DeleteModel(
            name='ProductOrServiceCategory',
        ),
    ]
