# Generated by Django 4.0.2 on 2022-03-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_subaccount_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialbalance',
            name='sub_account',
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='title',
            field=models.CharField(choices=[('حساب عادی', 'حساب عادی'), ('سرمایه گذاری', 'سرمایه گذاری'), ('دارایی', 'دارایی'), ('ملک', 'ملک'), ('اثاثیه', 'اثاثیه'), ('مالیات', 'مالیات'), ('هزینه', 'هزینه'), ('فروش', 'فروش'), ('خرید', 'خرید'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color'),
        ),
        migrations.DeleteModel(
            name='SubAccount',
        ),
    ]
