# Generated by Django 4.1 on 2022-09-08 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_productorservice_product_or_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.bank', verbose_name='bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='sarresid_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 6, 59, 22, 367878, tzinfo=datetime.timezone.utc), verbose_name='تاریخ سررسید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='sayyad_no',
            field=models.CharField(default='erererer', max_length=50, verbose_name='شماره صیاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='serial_no',
            field=models.CharField(default='ddddddddddd', max_length=50, verbose_name='شماره سری و سریال چک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='accounting.account', verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='accounting.account', verbose_name='دریافت کننده'),
        ),
    ]
