# Generated by Django 4.0.2 on 2022-03-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_financialbalance_sub_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='row',
            field=models.IntegerField(blank=True, verbose_name='row'),
        ),
    ]
