# Generated by Django 4.0.2 on 2022-03-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_invoiceline_invoice_alter_invoiceline_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorservice',
            options={'verbose_name': 'ProductOrService', 'verbose_name_plural': 'ProductOrServices'},
        ),
    ]
