# Generated by Django 4.1 on 2022-09-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_cheque_bank_cheque_sarresid_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_date',
        ),
    ]
