# Generated by Django 4.1 on 2022-09-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_download_file'),
        ('accounting', '0018_remove_cheque_cheque_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleTransaction',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('employer_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_transaction_set', to='accounting.transaction', verbose_name='employer_transaction')),
                ('middle_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_transaction_set', to='accounting.transaction', verbose_name='middle_transaction')),
            ],
            options={
                'verbose_name': 'DoubleTransaction',
                'verbose_name_plural': 'DoubleTransactions',
            },
            bases=('core.page',),
        ),
    ]
