# Generated by Django 4.1 on 2022-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default='1000', verbose_name='اولویت / ترتیب'),
        ),
    ]
