# Generated by Django 4.1 on 2022-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=200, verbose_name='value'),
        ),
    ]
