# Generated by Django 4.1 on 2022-10-20 23:24

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_productspecification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('گرم', 'گرم'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('لینک', 'لینک'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('گرم', 'گرم'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('لینک', 'لینک'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
        migrations.CreateModel(
            name='ProductOrServiceUnitName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('گرم', 'گرم'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('لینک', 'لینک'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], default='عدد', max_length=50, verbose_name='unit_name')),
                ('coef', models.IntegerField(default=1, verbose_name='coef')),
                ('product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.productorservice', verbose_name='productorservice')),
            ],
            options={
                'verbose_name': 'ProductOrServiceUnitName',
                'verbose_name_plural': 'ProductOrServiceUnitNames',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
