# Generated by Django 4.1 on 2022-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_invoiceline_unit_name_alter_price_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='row',
            field=models.IntegerField(blank=True, default=1, verbose_name='row'),
        ),
    ]
