# Generated by Django 4.1.3 on 2023-01-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_financialdocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('card_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت')),
                ('shaba_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا')),
                ('is_defult', models.BooleanField(default=False, verbose_name='default')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bank', verbose_name='bank')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccounts',
            },
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
