# Generated by Django 4.1.3 on 2023-01-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_bankaccount2_delete_bankaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount2',
            new_name='BankAccount',
        ),
    ]
