# Generated by Django 4.1.3 on 2023-01-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_bankaccount2_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
    ]
