# Generated by Django 4.1.3 on 2023-01-20 18:21

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_bankaccount_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'AccountTag',
                'verbose_name_plural': 'AccountTags',
            },
            bases=(models.Model, utility.utils.LinkHelper),
        ),
    ]
