# Generated by Django 4.1.3 on 2023-02-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_invoiceline_unit_name_alter_price_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='full_title'),
        ),
    ]
