# Generated by Django 4.1.3 on 2023-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_category_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('آماده تحویل', 'آماده تحویل'), ('تایید شده', 'تایید شده'), ('تحویل شده', 'تحویل شده'), ('کنسل شده', 'کنسل شده'), ('برگشت از تحویل', 'برگشت از تحویل'), ('تایید نهایی شده', 'تایید نهایی شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت'),
        ),
    ]
