# Generated by Django 4.0.2 on 2022-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='title',
            field=models.CharField(default='sdsd', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
