# Generated by Django 4.0.2 on 2022-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(verbose_name='distance'),
        ),
    ]
