# Generated by Django 3.2.13 on 2022-08-14 01:43

from django.db import migrations, models
import django.db.models.deletion
import utility.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image_priority'),
        ('accounting', '0009_auto_20220730_0457'),
        ('transport', '0002_rename_brand_vehicle_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='شکستنی است؟')),
                ('weight_unit', models.CharField(choices=[('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('تن', 'تن')], default='کیلوگرم', max_length=50, verbose_name='واحد وزن')),
                ('length', models.IntegerField(default=0, verbose_name='طول')),
                ('width', models.IntegerField(default=0, verbose_name='عرض')),
                ('height', models.IntegerField(default=0, verbose_name='ارتفاع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Luggage',
                'verbose_name_plural': 'Luggages',
            },
            bases=('core.page', utility.utils.LinkHelper),
        ),
    ]
