# Generated by Django 3.2.13 on 2022-04-27 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_vehicle_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='wage',
        ),
        migrations.AddField(
            model_name='workshift',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 20, 14, 35, 984129, tzinfo=utc), verbose_name='end_datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshift',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 20, 14, 38, 924611, tzinfo=utc), verbose_name='start_datetime'),
            preserve_default=False,
        ),
    ]
