# Generated by Django 4.0.2 on 2022-04-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_driver_color_alter_tripcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.area', verbose_name='area'),
        ),
    ]
