# Generated by Django 4.1 on 2022-09-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_doubletransaction'),
        ('transport', '0003_luggage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('doubletransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.doubletransaction')),
                ('load', models.CharField(blank=True, max_length=200, null=True, verbose_name='بار')),
                ('ghabz_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره قبض')),
                ('barnameh_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بارنامه')),
                ('date_sent', models.DateTimeField(verbose_name='تاریخ ارسال')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
            bases=('accounting.doubletransaction',),
        ),
    ]
