# Generated by Django 4.0.2 on 2022-04-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='paths',
            new_name='trip_paths',
        ),
    ]
