# Generated by Django 3.2.13 on 2022-04-30 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('date_fixed', models.DateTimeField(verbose_name='date_fixed')),
                ('profiles', models.ManyToManyField(blank=True, related_name='appointments', to='authentication.Profile', verbose_name='profiles')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
            bases=('core.page',),
        ),
    ]
