# Generated by Django 4.0.2 on 2022-04-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_icon_color'),
        ('authentication', '0003_profile_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('profiles', models.ManyToManyField(blank=True, related_name='appointments', to='authentication.Profile', verbose_name='profiles')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
            bases=('core.page',),
        ),
    ]
