# Generated by Django 4.0.2 on 2022-04-02 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_pagelocation'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_fixed',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 14, 29, 40, 981478, tzinfo=utc), verbose_name='date_fixed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.location', verbose_name='location'),
            preserve_default=False,
        ),
    ]
