# Generated by Django 3.2.13 on 2022-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20220730_0457'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='accounting.Account', verbose_name='accounts'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('تایید شده', 'تایید شده'), ('انجام شده', 'انجام شده'), ('کنسل شده', 'کنسل شده')], default='پیش نویس', max_length=50, verbose_name='status'),
        ),
    ]
