# Generated by Django 4.0.2 on 2022-04-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_pagelocation'),
        ('scheduler', '0002_appointment_date_fixed_appointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.location', verbose_name='location'),
        ),
    ]
